# Site settings
title:          Steve Learns Computer Science
description:    "Steve Learns Computer Science"
url:            "https://stackdragon.github.io"

# Author
author:
  name:         Steve
  url:          http://www.stevep.net
  email:        

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins_dir:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
